import type { TranscriptProvider, TranscriptRequest, TranscriptResult } from "./types";
import { TranscriptUnavailableError } from "./types";

export class IngestedTextTranscriptProvider implements TranscriptProvider {
  readonly name = "get_notes_ingested_text";

  async canHandle(input: TranscriptRequest) {
    return input.sourceType === "get_notes" && input.metadata?.hasTranscript === true;
  }

  async fetch(input: TranscriptRequest): Promise<TranscriptResult> {
    const text = input.inputText?.trim();
    if (!text) throw new TranscriptUnavailableError("Get 笔记没有返回可用的口述正文");
    return {
      language: input.language ?? "zh-CN",
      isAutoGenerated: true,
      segments: [{ startMs: 0, endMs: 0, text }],
      provider: this.name,
      hasTimestamps: false,
      sourceUrl: input.sourceUrl,
      metadata: {
        provenance: input.metadata?.provenance ?? "verified_live",
        transcriptBoundary: "text_only_no_timestamps",
      },
    };
  }
}
