import type { TranscriptProvider, TranscriptResult } from "./types";

export class ManualTranscriptProvider implements TranscriptProvider {
  readonly name = "manual_upload";
  constructor(private readonly result: TranscriptResult) {}
  async canHandle() { return true; }
  async fetch() { return this.result; }
}

export function parseSrt(input: string): TranscriptResult {
  const blocks = input.replace(/\r/g, "").trim().split(/\n\n+/);
  const segments = blocks.flatMap((block) => {
    const lines = block.split("\n");
    const timeLineIndex = lines.findIndex((line) => line.includes("-->"));
    if (timeLineIndex < 0) return [];
    const [start, end] = lines[timeLineIndex].split("-->").map((value) => value.trim());
    const toMs = (value: string) => {
      const [h, m, rest] = value.replace(",", ".").split(":");
      return Math.round((Number(h) * 3600 + Number(m) * 60 + Number(rest)) * 1000);
    };
    return [{ startMs: toMs(start), endMs: toMs(end), text: lines.slice(timeLineIndex + 1).join(" ").trim() }];
  }).filter((segment) => segment.text);
  return { language: "und", isAutoGenerated: false, segments, provider: "manual_upload",hasTimestamps:true };
}

function vttMs(value:string){const parts=value.trim().replace(",",".").split(":");const seconds=parts.length===3?Number(parts[0])*3600+Number(parts[1])*60+Number(parts[2]):Number(parts[0])*60+Number(parts[1]);return Math.round(seconds*1000);}
export function parseVtt(input:string):TranscriptResult{const blocks=input.replace(/\r/g,"").replace(/^WEBVTT[^\n]*\n+/i,"").trim().split(/\n\n+/);const segments=blocks.flatMap(block=>{const lines=block.split("\n").filter(Boolean);const index=lines.findIndex(line=>line.includes("-->"));if(index<0)return[];const[start,end]=lines[index].split("-->").map(part=>part.trim().split(/\s+/)[0]);const text=lines.slice(index+1).join(" ").replace(/<[^>]+>/g,"").trim();return text?[{startMs:vttMs(start),endMs:vttMs(end),text}]:[]});return{language:"und",isAutoGenerated:false,segments,provider:"manual_upload",hasTimestamps:true};}
export function parsePlainTranscript(input:string):TranscriptResult{const text=input.trim();return{language:"und",isAutoGenerated:false,segments:text?[{startMs:0,endMs:0,text}]:[],provider:"manual_upload",hasTimestamps:false};}

export function parseTranscriptUpload(input:{name:string;text:string;language?:string}){const name=input.name.toLowerCase();const parsed=name.endsWith(".srt")?parseSrt(input.text):name.endsWith(".vtt")?parseVtt(input.text):name.endsWith(".txt")?parsePlainTranscript(input.text):null;if(!parsed)throw new Error("只支持 .srt、.vtt 或 .txt 字幕");if(!parsed.segments.length)throw new Error("字幕文件没有可读取的内容");return{...parsed,language:input.language?.trim()||parsed.language};}
