import type { TranscriptProvider, TranscriptResult } from "./types";

export class ManualTranscriptProvider implements TranscriptProvider {
  readonly name = "manual_upload";
  constructor(private readonly result: TranscriptResult) {}
  async canHandle() { return true; }
  async fetch() { return this.result; }
}

export function parseSrt(input: string): TranscriptResult {
  const blocks = input.replace(/\r/g, "").trim().split(/\n\n+/);
  const segments = blocks.flatMap((block) => {
    const lines = block.split("\n");
    const timeLineIndex = lines.findIndex((line) => line.includes("-->"));
    if (timeLineIndex < 0) return [];
    const [start, end] = lines[timeLineIndex].split("-->").map((value) => value.trim());
    const toMs = (value: string) => {
      const [h, m, rest] = value.replace(",", ".").split(":");
      return Math.round((Number(h) * 3600 + Number(m) * 60 + Number(rest)) * 1000);
    };
    return [{ startMs: toMs(start), endMs: toMs(end), text: lines.slice(timeLineIndex + 1).join(" ").trim() }];
  }).filter((segment) => segment.text);
  return { language: "und", isAutoGenerated: false, segments, provider: "manual_upload" };
}
