export type TranscriptRequest = {
  videoId: string;
  sourceUrl: string;
  preferredLanguages?: string[];
  audioUrl?: string;
};

export type TranscriptResult = {
  language: string;
  isAutoGenerated: boolean;
  segments: Array<{ startMs: number; endMs: number; text: string }>;
  provider: string;
  confidence?: number;
};

export interface TranscriptProvider {
  name: string;
  canHandle(input: TranscriptRequest): Promise<boolean>;
  fetch(input: TranscriptRequest): Promise<TranscriptResult>;
}
