import{spawn}from"node:child_process";
import{mkdtemp,readFile,readdir,rm}from"node:fs/promises";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{RetryableJobError}from"../jobs";
import{parseVtt}from"./manual";
import{TranscriptUnavailableError,type TranscriptProvider,type TranscriptRequest,type TranscriptResult}from"./types";

function run(args:string[],timeoutMs=120_000){
  return new Promise<void>((resolve,reject)=>{
    const child=spawn(process.env.YT_DLP_PATH??"yt-dlp",args,{stdio:["ignore","ignore","pipe"]});
    let stderr="";
    child.stderr.on("data",chunk=>{stderr+=String(chunk).slice(0,4000)});
    const timer=setTimeout(()=>{child.kill("SIGTERM");reject(new Error("yt-dlp 字幕获取超时"));},timeoutMs);
    child.on("error",reject);
    child.on("close",code=>{
      clearTimeout(timer);
      if(code===0)resolve();
      else if(/429|too many requests|rate.?limit/i.test(stderr))reject(new RetryableJobError("YouTube transcript rate limited",Number(process.env.TRANSCRIPT_RATE_LIMIT_RETRY_MS??900_000),"transcript_pipeline"));
      else reject(new Error(stderr.trim()||`yt-dlp 退出 ${code}`));
    });
  });
}

export class YtDlpTranscriptProvider implements TranscriptProvider{
  readonly name="yt_dlp";
  async canHandle(){return process.env.WORKER_RUNTIME==="true";}
  async fetch(input:TranscriptRequest):Promise<TranscriptResult>{
    if(process.env.WORKER_RUNTIME!=="true")throw new Error("yt-dlp 只允许在独立 Worker 中运行");
    const directory=await mkdtemp(join(tmpdir(),"signal-transcript-"));
    try{
      const languages=(input.preferredLanguages?.length?input.preferredLanguages:["zh-Hans","zh-Hant","zh","en"]).join(",");
      let auto=false;
      for(const mode of["--write-subs","--write-auto-subs"]){
        await run(["--skip-download",mode,"--sub-format","vtt","--sub-langs",languages,"--sleep-requests","1","--sleep-subtitles","2","--retries","3","--retry-sleep","exp=2:10","-o",join(directory,"subtitle.%(language)s.%(ext)s"),input.sourceUrl]).catch(error=>{if(mode==="--write-auto-subs"||error instanceof RetryableJobError)throw error;});
        const files=(await readdir(directory)).filter(name=>name.endsWith(".vtt"));
        if(files.length){
          const selected=files.sort((a,b)=>{const ai=a.includes("live_chat")?1:0;const bi=b.includes("live_chat")?1:0;return ai-bi||a.localeCompare(b);})[0];
          const parsed=parseVtt(await readFile(join(directory,selected),"utf8"));
          const language=selected.split(".").at(-2)??"und";
          return{...parsed,language,isAutoGenerated:auto,provider:this.name,sourceUrl:input.sourceUrl,metadata:{file:selected}};
        }
        auto=true;
      }
      throw new TranscriptUnavailableError("公开视频没有人工或自动字幕");
    }finally{
      await rm(directory,{recursive:true,force:true});
    }
  }
}
