import{spawn}from"node:child_process";
import{mkdtemp,readFile,readdir,rm}from"node:fs/promises";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{RetryableJobError}from"../jobs";
import{parseVtt}from"./manual";
import{TranscriptUnavailableError,type TranscriptProvider,type TranscriptRequest,type TranscriptResult}from"./types";

type SubtitleCatalog=Record<string,unknown[]>;

function processError(stderr:string,code:number|null){
  if(/429|too many requests|rate.?limit/i.test(stderr))return new RetryableJobError("YouTube transcript rate limited",Number(process.env.TRANSCRIPT_RATE_LIMIT_RETRY_MS??900_000),"transcript_pipeline");
  return new Error(stderr.trim()||`yt-dlp 退出 ${code}`);
}

function run(args:string[],timeoutMs=120_000){
  return new Promise<{stdout:string;stderr:string}>((resolve,reject)=>{
    const child=spawn(process.env.YT_DLP_PATH??"yt-dlp",args,{stdio:["ignore","pipe","pipe"]});
    let stdout="",stderr="",settled=false;
    child.stdout.on("data",chunk=>{if(stdout.length<8_000_000)stdout+=String(chunk)});
    child.stderr.on("data",chunk=>{if(stderr.length<32_000)stderr+=String(chunk)});
    const timer=setTimeout(()=>{if(settled)return;settled=true;child.kill("SIGTERM");reject(new Error("yt-dlp 字幕获取超时"));},timeoutMs);
    child.on("error",error=>{if(settled)return;settled=true;clearTimeout(timer);reject(error)});
    child.on("close",code=>{if(settled)return;settled=true;clearTimeout(timer);if(code===0)resolve({stdout,stderr});else reject(processError(stderr,code));});
  });
}

export function selectSubtitleLanguage(catalog:SubtitleCatalog,preferredLanguages:string[]){
  const available=Object.keys(catalog).filter(language=>language!=="live_chat");
  for(const preferred of preferredLanguages){if(available.includes(preferred))return preferred;}
  for(const preferred of preferredLanguages){const base=preferred.toLowerCase().split("-")[0];const match=available.find(language=>language.toLowerCase().split("-")[0]===base);if(match)return match;}
  return available[0]??null;
}

export class YtDlpTranscriptProvider implements TranscriptProvider{
  readonly name="yt_dlp";
  async canHandle(input:TranscriptRequest){if(process.env.WORKER_RUNTIME!=="true")return false;return input.sourceType?input.sourceType==="youtube":/(?:youtube\.com|youtu\.be)/i.test(input.sourceUrl);}
  async fetch(input:TranscriptRequest):Promise<TranscriptResult>{
    if(process.env.WORKER_RUNTIME!=="true")throw new Error("yt-dlp 只允许在独立 Worker 中运行");
    const directory=await mkdtemp(join(tmpdir(),"signal-transcript-"));
    try{
      const preferences=input.preferredLanguages?.length?input.preferredLanguages:["zh-Hans","zh-Hant","zh","en"];
      const metadataRun=await run(["--skip-download","--no-playlist","--dump-single-json","--sleep-requests","1","--retries","3","--retry-sleep","exp=2:10",input.sourceUrl]);
      const metadata=JSON.parse(metadataRun.stdout)as{subtitles?:SubtitleCatalog;automatic_captions?:SubtitleCatalog};
      const manualLanguage=selectSubtitleLanguage(metadata.subtitles??{},preferences);
      const automaticLanguage=manualLanguage?null:selectSubtitleLanguage(metadata.automatic_captions??{},preferences);
      const language=manualLanguage??automaticLanguage;
      if(!language)throw new TranscriptUnavailableError("公开视频没有人工或自动字幕");
      const auto=!manualLanguage;
      await run(["--skip-download","--no-playlist",auto?"--write-auto-subs":"--write-subs","--sub-format","vtt","--sub-langs",language,"--sleep-requests","1","--sleep-subtitles","2","--retries","3","--retry-sleep","exp=2:10","-o",join(directory,"subtitle.%(language)s.%(ext)s"),input.sourceUrl]);
      const files=(await readdir(directory)).filter(name=>name.endsWith(".vtt"));
      if(!files.length)throw new TranscriptUnavailableError("字幕元数据存在，但未下载到 VTT 文件");
      const selected=files.sort()[0];
      const parsed=parseVtt(await readFile(join(directory,selected),"utf8"));
      return{...parsed,language,isAutoGenerated:auto,provider:this.name,sourceUrl:input.sourceUrl,metadata:{file:selected,selectedTrack:language}};
    }finally{
      await rm(directory,{recursive:true,force:true});
    }
  }
}
