import{randomUUID}from"node:crypto";
import type{SupabaseClient}from"@supabase/supabase-js";
import{enqueueContentAnalysis}from"./analysis-queue";
import{enqueueJob}from"./ingest";
import{enqueueTranscriptFetch}from"./transcript-queue";

export type ProcessingRequestStatus="queued"|"fetching_transcript"|"translating_transcript"|"analyzing"|"ready"|"limited_ready"|"failed";
const activeStatuses:ProcessingRequestStatus[]=["queued","fetching_transcript","translating_transcript","analyzing"];

export async function readProcessingRequest(admin:SupabaseClient,workspaceId:string,contentId:string){const{data,error}=await admin.from("content_processing_requests").select("id,status,current_stage,transcript_job_id,translation_job_id,analysis_job_id,requested_at,started_at,completed_at,error,metadata").eq("workspace_id",workspaceId).eq("content_id",contentId).order("requested_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data;}

export async function requestDeepProcessing(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestedBy?:string|null}){
  const{data:content,error}=await admin.from("content_items").select("id,external_id,material_content_hash,analysis_input_hash,source:sources!inner(type)").eq("workspace_id",input.workspaceId).eq("id",input.contentId).single();if(error||!content)throw new Error(error?.message??"内容不存在");const source=content.source as unknown as{type:string};if(source.type!=="youtube")throw new Error("当前只有 YouTube 内容支持手动深度处理");
  const{data:existing,error:existingError}=await admin.from("content_processing_requests").select("id,status,current_stage,transcript_job_id,translation_job_id,analysis_job_id,requested_at,started_at,completed_at,error,metadata").eq("workspace_id",input.workspaceId).eq("content_id",input.contentId).in("status",activeStatuses).maybeSingle();if(existingError)throw new Error(existingError.message);if(existing)return{request:existing,jobs:[existing.transcript_job_id,existing.translation_job_id,existing.analysis_job_id].filter(Boolean),created:false};
  const row={workspace_id:input.workspaceId,content_id:input.contentId,requested_by:input.requestedBy??null,mode:"deep",status:"queued",current_stage:"request_deep_processing",metadata:{requestId:randomUUID()}};
  const inserted=await admin.from("content_processing_requests").insert(row).select("id,status,current_stage,transcript_job_id,translation_job_id,analysis_job_id,requested_at,started_at,completed_at,error,metadata").single();
  if(inserted.error?.code==="23505"){const current=await readProcessingRequest(admin,input.workspaceId,input.contentId);if(!current)throw new Error("读取已有深度处理请求失败");return{request:current,jobs:[current.transcript_job_id,current.translation_job_id,current.analysis_job_id].filter(Boolean),created:false};}
  if(inserted.error||!inserted.data)throw new Error(inserted.error?.message??"创建深度处理请求失败");const request=inserted.data;
  const transcriptJob=await enqueueTranscriptFetch(admin,{workspaceId:input.workspaceId,contentId:input.contentId,contentHash:content.material_content_hash??content.analysis_input_hash??"legacy",sourceType:"youtube",videoId:content.external_id,processingRequestId:request.id,priority:110});
  const startedAt=new Date().toISOString();const updated=await admin.from("content_processing_requests").update({status:"fetching_transcript",current_stage:"fetch_transcript",transcript_job_id:transcriptJob.id,started_at:startedAt}).eq("id",request.id).select("id,status,current_stage,transcript_job_id,translation_job_id,analysis_job_id,requested_at,started_at,completed_at,error,metadata").single();if(updated.error||!updated.data)throw new Error(updated.error?.message??"更新深度处理请求失败");await admin.from("content_items").update({processing_mode:"fetching_transcript"}).eq("id",input.contentId);
  return{request:updated.data,jobs:[transcriptJob.id],created:true};
}

export async function markProcessingStage(admin:SupabaseClient,input:{workspaceId:string;requestId:string;contentId:string;status:ProcessingRequestStatus;stage:string;jobField?:"translation_job_id"|"analysis_job_id";jobId?:string;metadata?:Record<string,unknown>;error?:string|null}){
  const patch:Record<string,unknown>={status:input.status,current_stage:input.stage,error:input.error??null};if(input.jobField&&input.jobId)patch[input.jobField]=input.jobId;if(["ready","limited_ready","failed"].includes(input.status))patch.completed_at=new Date().toISOString();
  const{data:current}=await admin.from("content_processing_requests").select("metadata").eq("workspace_id",input.workspaceId).eq("id",input.requestId).maybeSingle();if(input.metadata)patch.metadata={...(current?.metadata as Record<string,unknown>??{}),...input.metadata};
  const result=await admin.from("content_processing_requests").update(patch).eq("workspace_id",input.workspaceId).eq("id",input.requestId);if(result.error)throw new Error(result.error.message);const content=await admin.from("content_items").update({processing_mode:input.status}).eq("workspace_id",input.workspaceId).eq("id",input.contentId);if(content.error)throw new Error(content.error.message);
}

export async function enqueueTranscriptTranslation(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string;transcriptId:string}){const job=await enqueueJob(admin,{workspaceId:input.workspaceId,type:"translate_transcript",idempotencyKey:`translate_transcript:${input.requestId}:${input.transcriptId}:zh-CN`,payload:{contentId:input.contentId,processingRequestId:input.requestId,transcriptId:input.transcriptId,targetLanguage:"zh-CN"},priority:105});await markProcessingStage(admin,{...input,status:"translating_transcript",stage:"translate_transcript",jobField:"translation_job_id",jobId:job.id});return job;}

export async function enqueueDeepAnalysis(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string;limited?:boolean;reason?:string}){const job=await enqueueContentAnalysis(admin,{workspaceId:input.workspaceId,contentId:input.contentId,type:"analyze_creator_content",priority:100,processingRequestId:input.requestId,limited:input.limited});await markProcessingStage(admin,{...input,status:"analyzing",stage:"analyze_creator_content",jobField:"analysis_job_id",jobId:job.id,metadata:{limited:input.limited===true,...(input.reason?{limitedReason:input.reason}:{})}});return job;}

export async function enqueueFinalizeProcessing(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string}){return enqueueJob(admin,{workspaceId:input.workspaceId,type:"finalize_processing_request",idempotencyKey:`finalize_processing_request:${input.requestId}`,payload:{contentId:input.contentId,processingRequestId:input.requestId},priority:200});}

async function persistTopicOpportunity(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string}){const{data:analysis,error}=await admin.from("creator_content_analyses").select("topic_opportunity,evidence_refs,content:content_items(title,summary)").eq("workspace_id",input.workspaceId).eq("content_id",input.contentId).eq("is_current",true).eq("status","ready").maybeSingle();if(error)throw new Error(error.message);const opportunity=analysis?.topic_opportunity&&typeof analysis.topic_opportunity==="object"?analysis.topic_opportunity as Record<string,unknown>:{};if(opportunity.available!==true)return null;const creationSource=`deep_processing:${input.contentId}`;const{data:existing,error:existingError}=await admin.from("topic_candidates").select("id").eq("workspace_id",input.workspaceId).eq("creation_source",creationSource).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existingError)throw new Error(existingError.message);let topicId=existing?.id as string|undefined;if(!topicId){const content=Array.isArray(analysis?.content)?analysis.content[0]:analysis?.content;const{data:created,error:createError}=await admin.from("topic_candidates").insert({workspace_id:input.workspaceId,topic:String(opportunity.angle??content?.title??"待确认选题"),target_audience:String(opportunity.audience??"当前账号受众"),differentiated_angle:String(opportunity.difference??"待确认"),validation_task:String(opportunity.validationTask??"完成一次真实实测"),why_now:content?.summary??null,status:"candidate",creation_source:creationSource}).select("id").single();if(createError||!created)throw new Error(createError?.message??"创建证据选题失败");topicId=created.id;}const refs=Array.isArray(analysis?.evidence_refs)?analysis.evidence_refs.filter((item):item is string=>typeof item==="string"):[];const segmentIds=refs.filter(item=>item.startsWith("segment:")).map(item=>item.slice(8));const{data:segments,error:segmentError}=segmentIds.length?await admin.from("transcript_segments").select("id,text,translated_text,start_ms").in("id",segmentIds):{data:[],error:null};if(segmentError)throw new Error(segmentError.message);const sources=[{workspace_id:input.workspaceId,topic_id:topicId,source_type:"content",source_id:input.contentId,purpose:"深度分析来源",excerpt:null,timestamp_ms:null},...(segments??[]).map(segment=>({workspace_id:input.workspaceId,topic_id:topicId,source_type:"segment",source_id:segment.id,purpose:"字幕证据",excerpt:segment.translated_text??segment.text,timestamp_ms:segment.start_ms}))];const existingSources=await admin.from("topic_sources").select("source_id").eq("workspace_id",input.workspaceId).eq("topic_id",topicId);if(existingSources.error)throw new Error(existingSources.error.message);const known=new Set((existingSources.data??[]).map(item=>item.source_id));const missing=sources.filter(item=>!known.has(item.source_id));if(missing.length){const saved=await admin.from("topic_sources").insert(missing);if(saved.error)throw new Error(saved.error.message);}return topicId;}

export async function finalizeProcessingRequest(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string}){const{data,error}=await admin.from("content_processing_requests").select("metadata").eq("workspace_id",input.workspaceId).eq("id",input.requestId).single();if(error||!data)throw new Error(error?.message??"深度处理请求不存在");const limited=(data.metadata as Record<string,unknown>|null)?.limited===true;const topicId=await persistTopicOpportunity(admin,input);await markProcessingStage(admin,{...input,status:limited?"limited_ready":"ready",stage:"finalize_processing_request",metadata:topicId?{topicId}:{}});return{status:limited?"limited_ready"as const:"ready"as const,topicId};}

export async function failProcessingRequest(admin:SupabaseClient,input:{workspaceId:string;contentId:string;requestId:string;error:string}){await markProcessingStage(admin,{...input,status:"failed",stage:"failed",error:input.error});}
