import type { SupabaseClient } from "@supabase/supabase-js";
import { enqueueJob } from "./ingest";

function record(value:unknown):Record<string,unknown>{return value&&typeof value==="object"?value as Record<string,unknown>:{};}

export async function enqueueTranscriptFetch(admin:SupabaseClient,input:{workspaceId:string;contentId:string;contentHash:string;sourceType:"youtube"|"get_notes";videoId?:string;postId?:string;priority?:number}){
  const idempotencyKey=input.sourceType==="get_notes"?`fetch_transcript:get_notes_text:${input.contentId}:${input.contentHash}`:`fetch_transcript:${input.contentId}:${input.contentHash}`;const pending=await admin.from("jobs").select("id,idempotency_key,payload").eq("workspace_id",input.workspaceId).eq("type","fetch_transcript").in("status",["queued","blocked"]).contains("payload",{contentId:input.contentId});if(pending.error)throw new Error(pending.error.message);const obsoleteIds=(pending.data??[]).filter(item=>record(item.payload).contentHash!==input.contentHash||item.idempotency_key!==idempotencyKey).map(item=>item.id);if(obsoleteIds.length){const cancelled=await admin.from("jobs").update({status:"cancelled",result:{reason:"superseded_by_new_transcript_input",contentHash:input.contentHash},locked_at:null,locked_by:null,lease_expires_at:null,heartbeat_at:null}).in("id",obsoleteIds);if(cancelled.error)throw new Error(cancelled.error.message);}
  const job=await enqueueJob(admin,{workspaceId:input.workspaceId,type:"fetch_transcript",idempotencyKey,payload:{contentId:input.contentId,contentHash:input.contentHash,sourceType:input.sourceType,...(input.videoId?{videoId:input.videoId}:{}),...(input.postId?{postId:input.postId}:{})},priority:input.priority??70});if(job.status!=="cancelled")return job;const restored=await admin.from("jobs").update({status:"queued",run_at:new Date().toISOString(),attempt:0,result:null,error:null,locked_at:null,locked_by:null,lease_expires_at:null,heartbeat_at:null}).eq("id",job.id).select("id,type,status,priority,payload,idempotency_key,created_at").single();if(restored.error||!restored.data)throw new Error(restored.error?.message??"恢复字幕任务失败");return restored.data;
}
