import { expect,test } from "@playwright/test";

test("V2 five-part information architecture is usable in explicit demo isolation",async({page})=>{
  await page.goto("/today");
  await expect(page.getByText("演示模式 · 不含真实数据")).toBeVisible();
  await expect(page.getByRole("heading",{name:"今天，先看真正重要的变化"})).toBeVisible();
  await expect(page.getByText("47 条新增")).toHaveCount(0);
  await expect(page.getByText("92 分")).toHaveCount(0);
  for(const label of ["今日","AI 动态","博主动态","学习与选题","来源"])await expect(page.getByRole("link",{name:label,exact:true})).toBeVisible();
  await page.goto("/ai-news");await expect(page.getByRole("heading",{name:"AI 世界今天发生了什么"})).toBeVisible();
  await page.goto("/creators");await expect(page.getByRole("heading",{name:"我关注的博主发了什么"})).toBeVisible();
  await page.goto("/learning");await expect(page.getByRole("heading",{name:"把值得看的内容，变成自己的判断"})).toBeVisible();
  await page.goto("/sources");await expect(page.getByRole("heading",{name:"来源",exact:true})).toBeVisible();
});

test("empty demo workspace never invents live records",async({page})=>{
  await page.goto("/today");
  await expect(page.getByText("今天的简报还没有生成")).toBeVisible();
  await expect(page.getByText("这一天还没有可展示的 AI 事件")).toBeVisible();
  await expect(page.getByText("这一天还没有同步到博主新内容")).toBeVisible();
  const health=await page.request.get("/api/health");expect(health.ok()).toBeTruthy();expect((await health.json()).mode).toBe("demo");
});

test("manual sync returns an asynchronous queue response",async({page})=>{
  const response=await page.request.post("/api/sync/run",{data:{sources:["aihot","youtube"]}});expect(response.status()).toBe(202);const payload=await response.json();expect(payload.ok).toBeTruthy();expect(payload.jobs).toEqual([]);
});

test("YouTube iframe src stays stable when transcript seek changes position",async({page})=>{
  await page.route("**/api/learning/fake-content",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({mode:"live",detail:{content:{id:"fake-content",sourceType:"youtube",platform:"YouTube",creatorName:"真实频道",creatorAvatarUrl:null,publishedAt:"2026-08-17T00:00:00Z",durationSeconds:600,title:"播放器稳定性测试",translatedTitle:null,summary:"使用真实时间轴测试 seekTo",thumbnailUrl:null,canonicalUrl:"https://www.youtube.com/watch?v=dQw4w9WgXcQ",contentKind:"video",hasTranscript:true,interactionAvailable:false,recommendation:"deep_learn",recommendationReason:"有字幕",learningTakeaways:["时间轴"],topicOpportunity:null,learningScore:90,topicSignalScore:10,analysisMessage:null,analysisStatus:"ready",state:{isRead:false,isSaved:false,watchLater:false,isIgnored:false,notInterested:false,queuedLearning:true},body:null,embedUrl:"https://www.youtube.com/embed/dQw4w9WgXcQ",chapters:[],transcriptStatus:"ready"},session:{id:"session",status:"learning",goal:"测试",positionMs:0,watchedMs:0},transcript:{status:"ready",language:"en",provider:"fixture_provider",isAutoGenerated:false,hasTimestamps:true,failureReason:null,segments:[{id:"seg-1",startMs:1000,endMs:3000,text:"First",translatedText:null},{id:"seg-2",startMs:8000,endMs:10000,text:"Second",translatedText:null}],plainText:null},analysis:{learningRecommendation:"deep_learn",learningReason:"有真实字幕",corePoints:["测试"]},notes:[],knowledgeCards:[],practiceTasks:[],quiz:null}}) }));
  await page.goto("/learning/fake-content");const iframe=page.getByTestId("youtube-player");await expect(iframe).toBeVisible();const before=await iframe.getAttribute("src");await page.getByRole("button",{name:/Second/}).click();await expect(page.getByText("当前位置 00:08")).toBeVisible();expect(await iframe.getAttribute("src")).toBe(before);
});
