"use client";
import{ArrowRight,Bookmark,CalendarDays,ExternalLink,Lightbulb,RefreshCw,ThumbsDown,X}from"lucide-react";import{useCallback,useEffect,useState}from"react";import type{TodayEvent,CrossSignal}from"../../lib/domain/signal-desk";import{apiFetch}from"../../lib/client/api";
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai"}).format(new Date())}const dateTime=new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"});
export function AINewsPage(){const[date,setDate]=useState(today);const[events,setEvents]=useState<TodayEvent[]>([]);const[crossSignals,setCrossSignals]=useState<CrossSignal[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[selected,setSelected]=useState<TodayEvent|null>(null);const[topic,setTopic]=useState("");const[angle,setAngle]=useState("");const[notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const data=await apiFetch<{events:TodayEvent[];crossSignals:CrossSignal[]}>(`/api/ai-news?date=${date}`);setEvents(data.events);setCrossSignals(data.crossSignals)}catch(reason){setError(reason instanceof Error?reason.message:"读取失败")}finally{setLoading(false)}},[date]);useEffect(()=>{void load()},[load]);
  async function eventAction(id:string,action:string){await apiFetch(`/api/events/${id}/action`,{method:"POST",body:JSON.stringify({action})});setNotice(action==="saved"?"事件已保存":"已记录为不感兴趣")}
  function openTopic(event:TodayEvent){setSelected(event);setTopic(event.title);setAngle(event.contentOpportunity??"")}
  async function createTopic(){if(!selected||!topic.trim())return;await apiFetch("/api/topics",{method:"POST",body:JSON.stringify({directions:[{topic,type:"观点判断型",differentiatedAngle:angle,whyNow:selected.happened,validationTask:"核对一手来源，并完成一次与当前账号受众相关的真实验证"}],sources:[{type:"event",id:selected.id,excerpt:selected.happened}]})});setSelected(null);setNotice("选题已创建，并保留了这个事件作为真实证据")}
  return<div className="v2-page"><header className="v2-page-header"><div><div className="v2-date"><CalendarDays size={15}/>AIHot · 真实事件流</div><h1>AI 世界今天发生了什么</h1><p>同一事件合并展示；事实、来源说法、媒体解释和未确认信息分别保留。</p></div><div className="v2-header-actions"><label className="v2-date-picker"><input aria-label="日期" type="date" max={today()}value={date}onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>void load()}><RefreshCw size={16}/>刷新</button></div></header>
    {notice&&<div className="v2-success">{notice}<button onClick={()=>setNotice(null)}><X size={14}/></button></div>}{error&&<div className="v2-error">{error}</div>}
    <div className="v2-news-summary"><strong>{loading?"—":events.length}</strong><span>个已聚类事件</span><p>默认隐藏内部数字分；重要性只显示“重大、值得关注、了解即可”。</p></div>
    <section className="v2-editorial-section"><div className="v2-section-heading"><div><span>01</span><div><h2>事件编辑台</h2><p>先看发生了什么，再回到真实来源核对。</p></div></div></div>
      {events.length?<div className="v2-full-event-list">{events.map(event=><article key={event.id}><header><span className={`level-${event.level}`}>{event.level}</span><span>{event.category}</span><time>{event.publishedAt?dateTime.format(new Date(event.publishedAt)):"时间待确认"}</time></header><h2>{event.title}</h2><div className="v2-event-body"><div><h3>发生了什么</h3><p>{event.happened??"暂无可核对摘要"}</p></div><div><h3>真正变化</h3><p>{event.realChange??"等待分析"}</p></div><div><h3>为什么重要</h3><p>{event.whyImportant??"等待分析"}</p></div><div><h3>为什么与你有关</h3><p>{event.whyRelevant??"等待结合当前内容画像分析"}</p></div></div><div className="v2-evidence-line"><strong>证据</strong><span>{event.primarySource?"1 个主要来源":"暂无主要来源"}</span><span>{event.secondarySourceCount} 个二手来源</span><span>{event.relatedCreatorCount} 条相关博主内容</span></div>{event.contentOpportunity&&<p className="v2-opportunity"><Lightbulb size={16}/><span><strong>内容机会</strong>{event.contentOpportunity}</span></p>}<footer>{event.evidence.map(item=>item.url?<a key={item.id}href={item.url}target="_blank"rel="noreferrer">{item.sourceName}<ExternalLink size={13}/></a>:null)}<div><button onClick={()=>void eventAction(event.id,"saved")}><Bookmark size={15}/>保存</button><button onClick={()=>void eventAction(event.id,"not_interested")}><ThumbsDown size={15}/>不感兴趣</button><button className="primary"onClick={()=>openTopic(event)}><Lightbulb size={15}/>转为选题</button></div></footer></article>)}</div>:<div className="v2-inline-empty"><strong>{loading?"正在读取并合并事件…":"这一天没有可展示的事件"}</strong><p>页面不会放入固定 AI 新闻。请到来源页运行 AIHot 同步，或切换到有数据的日期。</p></div>}
    </section>
    <section className="v2-editorial-section"><div className="v2-section-heading"><div><span>02</span><div><h2>交叉信号</h2><p>只有主题同时出现在不同来源时才会出现。</p></div></div></div>{crossSignals.length?<div className="v2-cross-grid">{crossSignals.map(signal=><article key={signal.id}><small>{signal.trendStatus} · {signal.windowLabel}</small><h3>{signal.title}</h3><p>AIHot {signal.aihotCount} · YouTube {signal.youtubeCount} · 国内竞品 {signal.competitorCount}</p><dl><dt>国内外表达差异</dt><dd>{signal.expressionDifference??"等待足够证据"}</dd><dt>差异化选题</dt><dd>{signal.differentiatedTopic??"等待足够证据"}</dd></dl></article>)}</div>:<div className="v2-inline-empty compact"><strong>暂时没有达到门槛的跨来源主题</strong><p>至少需要两个不同来源围绕同一主题出现；单条内容不会被包装成趋势。</p></div>}</section>
    {selected&&<dialog open aria-modal="true"aria-label="创建选题"className="v2-modal-backdrop"><section className="v2-topic-modal"><button className="close"onClick={()=>setSelected(null)}><X/></button><small>基于真实事件创建</small><h2>把证据变成你的选题</h2><label>选题标题<input value={topic}onChange={e=>setTopic(e.target.value)}/></label><label>差异化角度<textarea value={angle}onChange={e=>setAngle(e.target.value)}placeholder="你准备亲自验证什么，或补充什么不同视角？"/></label><p>将关联事件 ID、来源和创建时间；不会只复制原始标题。</p><button className="v2-primary"onClick={()=>void createTopic()}>创建选题 <ArrowRight size={16}/></button></section></dialog>}
  </div>}
