"use client";
import{ArrowRight,BookOpen,CheckCircle2,Clock3,FileCheck2,Lightbulb,RefreshCw}from"lucide-react";import Link from"../ui/app-link";import{useCallback,useEffect,useMemo,useState}from"react";import type{CreatorItem}from"../../lib/domain/signal-desk";import{apiFetch}from"../../lib/client/api";
type LearningItem={sessionId:string;status:string;goal:string;positionMs:number;watchedMs:number;content:CreatorItem};type Topic={id:string;topic:string;target_audience:string|null;pain_point:string|null;differentiated_angle:string|null;why_now:string|null;validation_task:string|null;recommended_format:string|null;risk:unknown;status:string;creation_source:string;sources:Array<{id:string;source_type:string;source_id:string;excerpt:string|null;timestamp_ms:number|null}>};
const tabs=[{key:"queued",label:"待学习",icon:Clock3},{key:"learning",label:"学习中",icon:BookOpen},{key:"completed",label:"已完成",icon:CheckCircle2},{key:"practice",label:"待实践",icon:FileCheck2}];
export function LearningHub(){const[tab,setTab]=useState("queued");const[items,setItems]=useState<LearningItem[]>([]);const[topics,setTopics]=useState<Topic[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const[learning,topicData]=await Promise.all([apiFetch<{items:LearningItem[]}>("/api/learning"),apiFetch<{items:Topic[]}>("/api/topics")]);setItems(learning.items);setTopics(topicData.items)}catch(reason){setError(reason instanceof Error?reason.message:"读取失败")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const visible=useMemo(()=>items.filter(item=>item.status===tab),[items,tab]);
  async function topicStatus(id:string,status:string){await apiFetch(`/api/topics/${id}`,{method:"PATCH",body:JSON.stringify({status})});setTopics(current=>current.map(topic=>topic.id===id?{...topic,status}:topic));setNotice(status==="confirmed"?"选题已确认，真实证据关系保持不变":"选题状态已保存")}
  return<div className="v2-page"><header className="v2-page-header"><div><div className="v2-date">学习队列与真实证据选题</div><h1>把值得看的内容，变成自己的判断</h1><p>播放进度、笔记、知识卡、实践任务和选题都会保存到工作区。</p></div><button className="v2-refresh-button"onClick={()=>void load()}><RefreshCw size={16}/>刷新</button></header>{notice&&<div className="v2-success">{notice}</div>}{error&&<div className="v2-error">{error}</div>}
    <section className="v2-learning-section"><div className="v2-section-heading"><div><span>01</span><div><h2>学习队列</h2><p>按真实状态推进，不使用固定“已完成”。</p></div></div></div><div className="v2-learning-tabs">{tabs.map(item=><button key={item.key}className={tab===item.key?"active":""}onClick={()=>setTab(item.key)}><item.icon size={16}/>{item.label}<span>{items.filter(value=>value.status===item.key).length}</span></button>)}</div>{visible.length?<div className="v2-learning-list">{visible.map(item=><article key={item.sessionId}>{item.content.thumbnailUrl?<img src={item.content.thumbnailUrl}alt=""/>:<div className="no-thumb">暂无封面</div>}<div><div className="v2-creator-meta"><span>{item.content.platform} · {item.content.creatorName}</span><small>{item.content.hasTranscript?"已有字幕":"暂无字幕"}</small></div><h3>{item.content.title}</h3><p>{item.goal}</p><div className="progress-line"><i style={{width:`${Math.min(100,item.content.durationSeconds?item.positionMs/(item.content.durationSeconds*10):0)}%`}}/><span>{item.positionMs?`已保存到 ${Math.floor(item.positionMs/60000)} 分钟`:"尚未开始"}</span></div></div><Link href={`/learning/${item.content.id}`}>{tab==="queued"?"开始学习":"继续学习"}<ArrowRight size={16}/></Link></article>)}</div>:<div className="v2-inline-empty compact"><strong>{loading?"正在读取学习状态…":`当前没有“${tabs.find(item=>item.key===tab)?.label}”内容`}</strong><p>在博主动态中点击“加入学习”，内容会带着真实来源进入这里。</p></div>}</section>
    <section className="v2-learning-section"><div className="v2-section-heading"><div><span>02</span><div><h2>选题机会</h2><p>每一条都必须能回到真实来源。</p></div></div></div>{topics.length?<div className="v2-topic-list">{topics.map(topic=><article key={topic.id}><header><span>{topic.recommended_format??"待确定形式"}</span><span>{topic.status}</span></header><h3>{topic.topic}</h3><dl><dt>目标人群</dt><dd>{topic.target_audience??"待补充"}</dd><dt>差异化角度</dt><dd>{topic.differentiated_angle??"待补充"}</dd><dt>为什么现在做</dt><dd>{topic.why_now??"待补充"}</dd><dt>最小验证任务</dt><dd>{topic.validation_task??"待补充"}</dd></dl><footer><span>{topic.sources?.length??0} 条真实证据</span><div>{topic.status==="candidate"&&<button onClick={()=>void topicStatus(topic.id,"confirmed")}><Lightbulb size={14}/>确认选题</button>}<button onClick={()=>void topicStatus(topic.id,"testing")}>进入验证</button></div></footer></article>)}</div>:<div className="v2-inline-empty compact"><strong>还没有真实证据选题</strong><p>从 AI 事件或博主内容点击“创建选题”，来源 ID 和时间戳会一起保存。</p></div>}</section>
  </div>}
