"use client";
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,ExternalLink,FileText,NotebookPen,Play,Save,Target,X}from"lucide-react";import Link from"next/link";import{useCallback,useEffect,useMemo,useRef,useState}from"react";import type{LearningDetail as Detail,TranscriptSegment}from"../../lib/domain/signal-desk";import{apiFetch}from"../../lib/client/api";
const tabs=["字幕","分析","笔记","知识与实践","测试"]as const;function clock(ms:number){const seconds=Math.floor(ms/1000);return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
export function LearningDetailPage({contentId}:{contentId:string}){const[detail,setDetail]=useState<Detail|null>(null);const[tab,setTab]=useState<(typeof tabs)[number]>("字幕");const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[position,setPosition]=useState(0);const[note,setNote]=useState("");const[noteType,setNoteType]=useState("judgement");const[cardTitle,setCardTitle]=useState("");const[taskTitle,setTaskTitle]=useState("");const[topicTitle,setTopicTitle]=useState("");const[topicAngle,setTopicAngle]=useState("");const iframe=useRef<HTMLIFrameElement|null>(null);const lastSaved=useRef(0);
  const load=useCallback(async()=>{try{const data=await apiFetch<{detail:Detail}>(`/api/learning/${contentId}`);setDetail(data.detail);setPosition(data.detail.session?.positionMs??0)}catch(reason){setError(reason instanceof Error?reason.message:"读取失败")}},[contentId]);useEffect(()=>{void load()},[load]);
  const activeSegment=useMemo(()=>detail?.transcript.segments.find(segment=>position>=segment.startMs&&position<segment.endMs)??null,[detail,position]);
  useEffect(()=>{function receive(event:MessageEvent){if(!iframe.current||event.source!==iframe.current.contentWindow)return;let data=event.data;try{if(typeof data==="string")data=JSON.parse(data)}catch{return}const time=data?.info?.currentTime;if(typeof time==="number")setPosition(Math.round(time*1000))}window.addEventListener("message",receive);const timer=window.setInterval(()=>iframe.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func:"getCurrentTime",args:[]}),"*"),1000);return()=>{window.removeEventListener("message",receive);window.clearInterval(timer)}},[]);
  useEffect(()=>{if(!detail||position<=0||Math.abs(position-lastSaved.current)<10_000)return;lastSaved.current=position;const timer=window.setTimeout(()=>void apiFetch(`/api/learning/${contentId}/progress`,{method:"POST",body:JSON.stringify({positionMs:position,watchedMs:position,status:"learning"})}).catch(()=>undefined),500);return()=>window.clearTimeout(timer)},[position,detail,contentId]);
  function seek(segment:TranscriptSegment|{startSeconds:number}){const seconds="startMs"in segment?segment.startMs/1000:segment.startSeconds;setPosition(seconds*1000);iframe.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func:"seekTo",args:[seconds,true]}),"*")}
  async function saveNote(){if(!note.trim())return;await apiFetch(`/api/learning/${contentId}/artifacts`,{method:"POST",body:JSON.stringify({kind:"note",content:note,noteType,timestampMs:position,transcriptSegmentId:activeSegment?.id})});setNote("");setNotice("笔记已保存，并关联当前内容位置");await load()}
  async function saveCard(){if(!cardTitle.trim()||!note.trim())return;await apiFetch(`/api/learning/${contentId}/artifacts`,{method:"POST",body:JSON.stringify({kind:"knowledge_card",title:cardTitle,content:note,timestampMs:position,transcriptSegmentId:activeSegment?.id})});setCardTitle("");setNotice("知识卡已写入工作区");await load()}
  async function saveTask(){if(!taskTitle.trim())return;await apiFetch(`/api/learning/${contentId}/artifacts`,{method:"POST",body:JSON.stringify({kind:"practice_task",title:taskTitle,purpose:"用自己的真实场景验证这条内容中的方法",steps:["确定一个真实场景","完成最小实测","记录结果与失败点"],completionCriteria:["保留输入、过程和结果"]})});setTaskTitle("");setNotice("实践任务已保存");await load()}
  async function createTopic(){if(!detail||!topicTitle.trim())return;await apiFetch("/api/topics",{method:"POST",body:JSON.stringify({directions:[{topic:topicTitle,type:"教程方法型",targetAudience:"当前账号受众",differentiatedAngle:topicAngle,whyNow:detail.content.summary,validationTask:"完成一次真实实测，并保存可以展示的过程证据"}],sources:[{type:"content",id:contentId,excerpt:detail.content.summary},{...(activeSegment?{type:"segment",id:activeSegment.id,excerpt:activeSegment.text,timestampMs:activeSegment.startMs}:{type:"content",id:contentId,excerpt:detail.content.summary})}]})});setTopicTitle("");setNotice("选题已创建，并关联当前内容与片段")}
  async function markComplete(){await apiFetch(`/api/learning/${contentId}/progress`,{method:"POST",body:JSON.stringify({positionMs:position,watchedMs:position,status:"completed"})});setNotice("学习状态已保存为完成");await load()}
  if(error)return<div className="v2-page"><Link href="/learning">返回学习列表</Link><div className="v2-error">{error}</div></div>;if(!detail)return<div className="v2-page"><div className="v2-inline-empty"><strong>正在加载真实内容…</strong></div></div>;
  const analysis=detail.analysis??{};const iframeUrl=detail.content.embedUrl?`${detail.content.embedUrl}?enablejsapi=1&start=${Math.floor(position/1000)}`:null;
  return<div className="v2-page v2-learning-detail"><Link className="v2-back"href="/learning"><ArrowLeft size={16}/>返回学习与选题</Link><header><div><span>{detail.content.platform} · {detail.content.creatorName}</span><h1>{detail.content.title}</h1><p>{detail.content.summary??"暂无摘要"}</p></div><button onClick={()=>void markComplete()}><CheckCircle2 size={16}/>标记完成</button></header>{notice&&<div className="v2-success">{notice}<button onClick={()=>setNotice(null)}><X size={14}/></button></div>}
    <div className="v2-study-layout"><section className="v2-player-column">{iframeUrl?<div className="v2-video-wrap"><iframe ref={iframe}src={iframeUrl}title={detail.content.title}allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"allowFullScreen/></div>:<div className="v2-document-view"><FileText size={34}/><strong>这是一条图文或竞品内容</strong><p>没有可嵌入的视频播放器，可阅读右侧原文与分析。</p>{detail.content.canonicalUrl&&<a href={detail.content.canonicalUrl}target="_blank"rel="noreferrer">打开原文<ExternalLink size={14}/></a>}</div>}<div className="v2-playback-state"><Play size={15}/><span>当前位置 {clock(position)}</span><i><b style={{width:`${detail.content.durationSeconds?Math.min(100,position/(detail.content.durationSeconds*10)):0}%`}}/></i><strong>{detail.session?.status??"queued"}</strong></div>{detail.content.chapters.length>0&&<div className="v2-chapters">{detail.content.chapters.map(chapter=><button key={`${chapter.startSeconds}-${chapter.title}`}onClick={()=>seek(chapter)}><time>{clock(chapter.startSeconds*1000)}</time>{chapter.title}</button>)}</div>}<div className="v2-learning-outputs"><button onClick={()=>setTab("笔记")}><NotebookPen size={17}/><span><strong>写笔记</strong><small>{detail.notes.length} 条已保存</small></span></button><button onClick={()=>setTab("知识与实践")}><Target size={17}/><span><strong>去实践</strong><small>{detail.practiceTasks.length} 个任务</small></span></button><button onClick={()=>setTab("知识与实践")}><BookOpen size={17}/><span><strong>知识卡</strong><small>{detail.knowledgeCards.length} 张</small></span></button></div></section>
      <section className="v2-study-panel"><nav>{tabs.map(item=><button key={item}className={tab===item?"active":""}onClick={()=>setTab(item)}>{item}</button>)}</nav>
        {tab==="字幕"&&<div className="v2-transcript-view"><div className="v2-boundary-banner">{detail.transcript.segments.length?"点击字幕可跳转到对应时间；当前播放位置会自动同步。":detail.content.transcriptStatus==="text_only_no_timestamps"?"来源提供了正文转录，但没有时间轴，无法精确跳转。":"暂无字幕；当前只依据标题、简介和章节做初步判断。"}</div>{detail.transcript.segments.length?detail.transcript.segments.map(segment=><button key={segment.id}className={activeSegment?.id===segment.id?"active":""}onClick={()=>seek(segment)}><time>{clock(segment.startMs)}</time><span><strong>{segment.text}</strong>{segment.translatedText&&<em>{segment.translatedText}</em>}</span></button>):detail.transcript.plainText?<div className="v2-plain-transcript">{detail.transcript.plainText}</div>:<div className="v2-panel-empty">暂无字幕</div>}</div>}
        {tab==="分析"&&<div className="v2-analysis-view">{detail.analysis?<><section><small>推荐结论</small><h3>{String(analysis.learningRecommendation??"等待分析")}</h3><p>{String(analysis.learningReason??"")}</p></section><section><small>内容骨架</small><ul>{Array.isArray(analysis.corePoints)?analysis.corePoints.map((point,index)=><li key={index}>{String(point)}</li>):<li>暂无结构化骨架</li>}</ul></section><section><small>值得学习</small><ul>{Array.isArray(analysis.learningTakeaways)?analysis.learningTakeaways.map((point,index)=><li key={index}>{String(point)}</li>):<li>暂无</li>}</ul></section><section><small>证据引用</small><p>{Array.isArray(analysis.evidenceRefs)?analysis.evidenceRefs.join(" · "):"暂无"}</p></section></>:<div className="v2-panel-empty"><strong>等待分析</strong><p>AI Provider 尚未配置；不会用固定文案伪装成该内容的分析结果。</p></div>}</div>}
        {tab==="笔记"&&<div className="v2-note-view"><div className="v2-current-quote"><time>{clock(position)}</time><p>{activeSegment?.text??"当前没有可关联的字幕片段"}</p></div><div className="v2-note-types">{[["judgement","我的判断"],["method","方法"],["question","问题"],["quote","引用"]].map(([value,label])=><button key={value}className={noteType===value?"active":""}onClick={()=>setNoteType(value)}>{label}</button>)}</div><textarea value={note}onChange={e=>setNote(e.target.value)}placeholder="写下自己的判断、疑问或可实践步骤…"/><button className="v2-primary"onClick={()=>void saveNote()}><Save size={15}/>保存笔记</button><div className="v2-saved-notes">{detail.notes.map(item=><article key={item.id}><small>{item.type}{item.timestampMs!==null?` · ${clock(item.timestampMs)}`:""}</small><p>{item.markdown}</p></article>)}</div></div>}
        {tab==="知识与实践"&&<div className="v2-output-view"><section><h3>创建知识卡</h3><input value={cardTitle}onChange={e=>setCardTitle(e.target.value)}placeholder="知识卡标题"/><p>知识卡正文使用“笔记”页当前编辑内容，并保留内容与片段来源。</p><button onClick={()=>void saveCard()}>写入知识卡</button></section><section><h3>创建实践任务</h3><input value={taskTitle}onChange={e=>setTaskTitle(e.target.value)}placeholder="要验证的真实任务"/><button onClick={()=>void saveTask()}>保存实践任务</button></section><section><h3>从当前内容创建选题</h3><input value={topicTitle}onChange={e=>setTopicTitle(e.target.value)}placeholder="你的教程或方法型方向"/><textarea value={topicAngle}onChange={e=>setTopicAngle(e.target.value)}placeholder="差异化角度与真实验证方式"/><button onClick={()=>void createTopic()}>创建选题 <ArrowRight size={14}/></button></section><div className="v2-output-records"><strong>已保存产物</strong><p>{detail.knowledgeCards.length} 张知识卡 · {detail.practiceTasks.length} 个实践任务</p></div></div>}
        {tab==="测试"&&<div className="v2-quiz-view">{detail.quiz?<><small>{detail.quiz.status}</small>{detail.quiz.questions.map(question=><article key={question.id}><h3>{question.prompt}</h3><textarea placeholder="写下你的回答"/></article>)}</>:<div className="v2-panel-empty"><strong>暂无基于真实内容生成的测试</strong><p>只有分析服务读取该内容后才会生成测试题；当前不会显示固定题目。</p></div>}</div>}
      </section></div></div>}
