"use client";
import{forwardRef,useCallback,useEffect,useImperativeHandle,useRef,useState}from"react";import{buildYouTubeEmbedUrl,nextWatchedMs}from"../../lib/youtube/player-progress";
type Player={seekTo(seconds:number,allowSeekAhead:boolean):void;getCurrentTime():number;getPlayerState():number;destroy():void};declare global{interface Window{YT?:{Player:new(element:HTMLIFrameElement,options:{events:{onReady:()=>void;onStateChange:(event:{data:number})=>void}})=>Player};onYouTubeIframeAPIReady?:()=>void}}
export type YouTubePlayerHandle={seekTo(seconds:number):void;getPositionMs():number;getWatchedMs():number;flush():Promise<void>};
function loadApi(){if(window.YT?.Player)return Promise.resolve();return new Promise<void>(resolve=>{const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{previous?.();resolve()};if(!document.querySelector('script[src="https://www.youtube.com/iframe_api"]')){const script=document.createElement("script");script.src="https://www.youtube.com/iframe_api";document.head.appendChild(script);}})}
export const YouTubePlayer=forwardRef<YouTubePlayerHandle,{embedUrl:string;initialPositionMs:number;initialWatchedMs:number;title:string;onPosition:(positionMs:number)=>void;onPersist:(positionMs:number,watchedMs:number)=>Promise<void>}>(({embedUrl,initialPositionMs,initialWatchedMs,title,onPosition,onPersist},ref)=>{const iframe=useRef<HTMLIFrameElement|null>(null);const player=useRef<Player|null>(null);const position=useRef(initialPositionMs);const watched=useRef(initialWatchedMs);const state=useRef(-1);const lastTick=useRef<number|null>(null);const lastPersisted=useRef(Date.now());const[src]=useState(()=>buildYouTubeEmbedUrl(embedUrl,initialPositionMs,typeof window!=="undefined"?window.location.origin:undefined));const[persistError,setPersistError]=useState(false);
  const flush=useCallback(async()=>{try{await onPersist(position.current,Math.round(watched.current));lastPersisted.current=Date.now();setPersistError(false)}catch{setPersistError(true)}},[onPersist]);
  useImperativeHandle(ref,()=>({seekTo(seconds){player.current?.seekTo(seconds,true);position.current=Math.round(seconds*1000);onPosition(position.current)},getPositionMs:()=>position.current,getWatchedMs:()=>Math.round(watched.current),flush}),[onPosition,flush]);
  useEffect(()=>{let disposed=false;void loadApi().then(()=>{if(disposed||!iframe.current||!window.YT?.Player)return;player.current=new window.YT.Player(iframe.current,{events:{onReady(){lastTick.current=Date.now()},onStateChange(event){const now=Date.now();watched.current=nextWatchedMs({watchedMs:watched.current,playerState:state.current,lastTickAt:lastTick.current,now});state.current=event.data;lastTick.current=now}}});});const timer=window.setInterval(()=>{const current=player.current;if(!current)return;const now=Date.now();watched.current=nextWatchedMs({watchedMs:watched.current,playerState:state.current,lastTickAt:lastTick.current,now});lastTick.current=now;const seconds=current.getCurrentTime();if(Number.isFinite(seconds)){position.current=Math.round(seconds*1000);onPosition(position.current)}if(now-lastPersisted.current>=12_000)void flush();},1_000);const pageHide=()=>void flush();const visibility=()=>{if(document.visibilityState==="hidden")void flush()};window.addEventListener("pagehide",pageHide);document.addEventListener("visibilitychange",visibility);return()=>{disposed=true;window.clearInterval(timer);window.removeEventListener("pagehide",pageHide);document.removeEventListener("visibilitychange",visibility);void flush();player.current?.destroy();player.current=null;}},[flush,onPosition]);
  return<div className="v2-video-wrap"><iframe ref={iframe}data-testid="youtube-player"src={src}title={title}allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"allowFullScreen/>{persistError&&<span className="v2-player-save-error">进度暂未保存</span>}</div>});YouTubePlayer.displayName="YouTubePlayer";
