export type SourceType = "aihot" | "youtube" | "get_notes";

export type EventLevel = "重大" | "值得关注" | "了解即可";
export type LearningRecommendation = "deep_learn" | "quick_scan" | "topic_signal" | "ignore" | "pending";
export type MetadataRecommendation = "process_first" | "quick_scan" | "topic_signal" | "low_priority" | "pending";
export type ProcessingMode = "metadata_only"|"deep_requested"|"fetching_transcript"|"translating_transcript"|"analyzing"|"ready"|"limited_ready"|"failed";

export type EvidenceLink = {
  id: string;
  title: string;
  url: string | null;
  sourceType: SourceType;
  sourceName: string;
  publishedAt: string | null;
};

export type TodayEvent = {
  id: string;
  level: EventLevel;
  category: string;
  publishedAt: string | null;
  title: string;
  sourceSummary:string|null;
  happened: string | null;
  realChange: string | null;
  whyImportant: string | null;
  whyRelevant: string | null;
  primarySource: EvidenceLink | null;
  secondarySourceCount: number;
  relatedCreatorCount: number;
  contentOpportunity: string | null;
  evidence: EvidenceLink[];
  claimBoundaries:Array<{claim:string;status:string;evidenceRef:string}>;
  unconfirmedClaims:string[];
  analysisStatus: "ready" | "pending" | "blocked";
};

export type CreatorItem = {
  id: string;
  sourceType: Exclude<SourceType, "aihot">;
  platform: "YouTube" | "抖音" | "其他";
  creatorName: string;
  creatorAvatarUrl: string | null;
  publishedAt: string | null;
  durationSeconds: number | null;
  title: string;
  translatedTitle: string | null;
  translatedSummary:string|null;
  translationStatus:"translating"|"ready"|"skipped"|"failed";
  summary: string | null;
  thumbnailUrl: string | null;
  canonicalUrl: string | null;
  contentKind:string|null;
  hasTranscript: boolean;
  interactionAvailable: boolean;
  recommendation: LearningRecommendation;
  metadataRecommendation:MetadataRecommendation;
  metadataBoundary:string;
  possibleValue:string|null;
  processingMode:ProcessingMode;
  recommendationReason: string | null;
  learningTakeaways: string[];
  topicOpportunity: string | null;
  learningScore:number|null;
  topicSignalScore:number|null;
  analysisMessage:string|null;
  analysisStatus: "ready" | "pending" | "blocked";
  state: { isRead:boolean;isSaved:boolean;watchLater:boolean;isIgnored:boolean;notInterested:boolean;queuedLearning:boolean };
};

export type CrossSignal = {
  id: string;
  title: string;
  aihotCount: number;
  youtubeCount: number;
  competitorCount: number;
  windowLabel: string;
  trendStatus: "刚刚出现" | "正在升温" | "持续关注" | "正在下降" | "孤立信号";
  trendBasis:string|null;
  windowCounts:{last24h:number;current7d:number;previous7d:number;baseline30d:number};
  expressionDifference: string | null;
  differentiatedTopic: string | null;
};

export type DailyBriefEntry = {
  id: string;
  kind: "event" | "trend" | "creator" | "topic";
  label: string;
  title: string;
  description: string | null;
  href: string;
};

export type TodayPayload = {
  mode: "live" | "demo";
  date: string;
  windowLabel: "过去 24 小时";
  stats: {
    importantEvents: number;
    creatorUpdates: number;
    deepLearning: number;
    topicOpportunities: number;
  };
  lastSyncedAt: string | null;
  briefStatus: "preparing"|"provisional"|"final"|"failed"|"missing";
  briefGeneratedAt:string|null;
  pendingTaskCount:number;
  brief: DailyBriefEntry[];
  events: TodayEvent[];
  creators: CreatorItem[];
  crossSignals: CrossSignal[];
  worker:{online:boolean;lastHeartbeat:string|null;lastScheduleAt:string|null;lastFinalBrief:string|null;queued:number;running:number;blocked:number;failed:number;deadLetter:number}|null;
};

export type ContentAction = "read" | "saved" | "watch_later" | "ignored" | "not_interested" | "queued_learning";

export type TranscriptSegment={id:string;startMs:number;endMs:number;text:string;translatedText:string|null};
export type LearningDetail={
  content:CreatorItem & {body:string|null;embedUrl:string|null;chapters:Array<{startSeconds:number;title:string}>;transcriptStatus:string};
  session:{id:string;status:string;goal:string;positionMs:number;watchedMs:number}|null;
  transcript:{status:string;language:string|null;provider:string|null;isAutoGenerated:boolean;hasTimestamps:boolean;failureReason:string|null;segments:TranscriptSegment[];plainText:string|null};
  analysis:Record<string,unknown>|null;
  notes:Array<{id:string;type:string;markdown:string;timestampMs:number|null;createdAt:string}>;
  knowledgeCards:Array<{id:string;title:string;type:string;content:string;createdAt:string}>;
  practiceTasks:Array<{id:string;name:string;purpose:string|null;status:string;result:string|null}>;
  quiz:{id:string;status:string;questions:Array<{id:string;type:string;prompt:string;rubric:Record<string,unknown>}>}|null;
};
