import type { ContentItem, TopicCandidate } from "./types";

export const demoContent: ContentItem[] = [
  {
    id: "yt-01",
    source: "YouTube",
    sourceType: "youtube",
    title: "How I Built a Research System That Compounds",
    author: "Build in Public",
    summary: "从来源分级、每周整理到判断规则，展示一个长期研究系统的完整工作流。",
    publishedAt: "今天 08:20",
    duration: "24:18",
    score: 89,
    learningScore: 94,
    topicScore: 81,
    topics: ["研究系统", "内容工作流"],
    status: "queued_learning",
    hasTranscript: true,
    provenance: "demo",
  },
  {
    id: "aihot-01",
    source: "AIHot",
    sourceType: "aihot",
    title: "AI 产品竞争开始转向长任务可靠性",
    author: "多个来源聚类",
    summary: "同一事件中的公开报道被合并，保留官方说法、媒体解释和待确认信息。",
    publishedAt: "今天 09:42",
    score: 92,
    learningScore: 63,
    topicScore: 86,
    topics: ["AI 智能体", "可靠性"],
    status: "unread",
    hasTranscript: false,
    provenance: "demo",
  },
  {
    id: "get-01",
    source: "Get 笔记",
    sourceType: "get_notes",
    title: "普通人做 AI 内容，真正卡住的不是工具",
    author: "珍妮丁丁说AI",
    summary: "竞品内容以具体焦虑场景开头，评论数据缺失，因此只作为内容信号。",
    publishedAt: "昨天 21:10",
    score: 78,
    learningScore: 55,
    topicScore: 88,
    topics: ["小白用户", "内容定位"],
    status: "saved",
    hasTranscript: false,
    provenance: "verified_live",
  },
  {
    id: "yt-02",
    source: "YouTube",
    sourceType: "youtube",
    title: "Building Reliable AI Agents: What Actually Works",
    author: "AI Engineer",
    summary: "从失败恢复、工具结果验证与上下文压缩三个角度解释智能体可靠性。",
    publishedAt: "昨天 18:40",
    duration: "38:05",
    score: 86,
    learningScore: 91,
    topicScore: 74,
    topics: ["AI 智能体", "工程实践"],
    status: "unread",
    hasTranscript: true,
    provenance: "demo",
  },
  {
    id: "get-02",
    source: "Get 笔记",
    sourceType: "get_notes",
    title: "我把 20 个 AI 工具删到只剩 4 个",
    author: "麻省理工长毛兔",
    summary: "标题强调反常识取舍，正文结构围绕使用场景而不是工具功能罗列。",
    publishedAt: "2 天前",
    score: 75,
    learningScore: 46,
    topicScore: 84,
    topics: ["工具选择", "效率"],
    status: "skimmed",
    hasTranscript: false,
    provenance: "verified_live",
  },
  {
    id: "aihot-02",
    source: "AIHot",
    sourceType: "aihot",
    title: "开源编程工具从代码补全转向完整工作流",
    author: "多个来源聚类",
    summary: "行业关注点逐步从单次生成质量转向计划、执行、验证与交付闭环。",
    publishedAt: "今天 07:15",
    score: 84,
    learningScore: 61,
    topicScore: 78,
    topics: ["AI 编程", "工作流"],
    status: "unread",
    hasTranscript: false,
    provenance: "demo",
  },
];

export const demoTopics: TopicCandidate[] = [
  {
    id: "topic-01",
    topic: "我停掉了每天 50 条 AI 日报，只保留这 3 个判断",
    audience: "被 AI 资讯淹没的内容创作者",
    painPoint: "看了很多但无法形成自己的判断",
    angle: "用真实一周处理记录对比信息数量与有效选题产出",
    whyNow: "多个工具都在强化聚合，用户开始从“更多”转向“更有用”",
    validationTask: "对比 7 天全量简报与三项行动模式的处理时间和产出",
    format: "口播 + 屏幕实测",
    score: 9,
    similarity: 18,
    status: "testing",
    evidenceCount: 6,
    type: "实测型",
  },
  {
    id: "topic-02",
    topic: "怎样搭一个不会越用越乱的个人 AI 情报系统",
    audience: "刚开始做内容系统的普通用户",
    painPoint: "收藏、笔记和选题散落在不同工具",
    angle: "从信号到学习再到选题，用四个对象解释最小系统",
    whyNow: "长任务智能体让自动采集更容易，但判断与沉淀仍是空缺",
    validationTask: "用一个真实事件跑通信号、知识卡和选题链路",
    format: "详细教程",
    score: 8,
    similarity: 24,
    status: "researching",
    evidenceCount: 5,
    type: "方法型",
  },
  {
    id: "topic-03",
    topic: "AI 摘要越好，你可能学得越少",
    audience: "依赖 AI 总结学习海外内容的人",
    painPoint: "以为看懂摘要就等于掌握方法",
    angle: "区分定位、理解、复现和迁移四个学习层次",
    whyNow: "越来越多产品把摘要直接包装成学习结果",
    validationTask: "对同一视频分别做摘要阅读和带测试学习，比较迁移题表现",
    format: "观点口播",
    score: 8,
    similarity: 11,
    status: "candidate",
    evidenceCount: 4,
    type: "观点型",
  },
];

export const transcriptSegments = [
  { id: "s1", time: "00:00", startMs: 0, text: "Most research systems fail because they optimize collection before deciding what deserves attention.", zh: "多数研究系统失败，是因为先优化采集，却没有先决定什么值得关注。" },
  { id: "s2", time: "02:34", startMs: 154000, text: "I separate signals, learning, knowledge, and decisions. They move at different speeds.", zh: "我把信号、学习、知识和决策分开，因为它们以不同速度变化。" },
  { id: "s3", time: "08:12", startMs: 492000, text: "A source is useful only when it repeatedly changes what you do, not when it merely looks authoritative.", zh: "一个来源只有反复改变你的行动时才有用，而不是因为它看起来权威。" },
  { id: "s4", time: "12:46", startMs: 766000, text: "Duplicate stories should become one event with multiple pieces of evidence.", zh: "重复报道应该合并为一个事件，同时保留多条证据。" },
  { id: "s5", time: "16:40", startMs: 1000000, text: "Every week, remove sources that create attention but produce no decisions.", zh: "每周都要移除那些只制造注意力、却无法带来决策的来源。" },
  { id: "s6", time: "21:18", startMs: 1278000, text: "The output of research is not a summary. It is a better question, rule, test, or decision.", zh: "研究的产出不是摘要，而是更好的问题、规则、测试或决策。" },
];

export const knowledgeCards = [
  { id: "k1", type: "判断规则", title: "来源有效性的最终标准", body: "一个来源是否值得保留，看它是否持续改变行动或决策，而不是更新频率和表面权威。", confidence: 88, sources: 3, tags: ["来源管理", "判断"] },
  { id: "k2", type: "方法", title: "四层研究对象", body: "将外部信号、学习过程、个人知识和内容选题分开管理，再通过证据关系连接。", confidence: 92, sources: 4, tags: ["研究系统", "工作流"] },
  { id: "k3", type: "警告", title: "摘要不能证明掌握", body: "快速摘要只适合判断是否值得投入；迁移能力需要测试、实践与用户判断。", confidence: 84, sources: 2, tags: ["学习", "AI 摘要"] },
  { id: "k4", type: "反例", title: "高频不等于高价值", body: "一个主题频繁出现，可能只是多平台转述同一事件，必须先去重和聚类。", confidence: 90, sources: 5, tags: ["去重", "事件聚类"] },
];

export const verifiedCompetitors = [
  { name: "珍妮丁丁说AI", platform: "抖音", signal: "真实账号连接", trend: "内容信号", topics: ["AI 小白", "效率工具"] },
  { name: "麻省理工长毛兔", platform: "抖音", signal: "真实账号连接", trend: "内容信号", topics: ["工具测评", "工作流"] },
  { name: "帧数燃烧", platform: "抖音", signal: "真实账号连接", trend: "内容信号", topics: ["AI 视频", "创作方法"] },
  { name: "宅不住的AI", platform: "抖音", signal: "真实账号连接", trend: "内容信号", topics: ["AI 工具", "实操"] },
];
