import{ANALYSIS_VERSION,CREATOR_PROMPT_VERSION,EVENT_PROMPT_VERSION,contentAnalysisInputHash}from"../lib/analysis/config";
import{sha256}from"../lib/dedupe";
import{getSupabaseAdmin}from"../lib/server/supabase-admin";

function record(value:unknown):Record<string,unknown>{return value&&typeof value==="object"?value as Record<string,unknown>:{};}
const admin=getSupabaseAdmin();
const{data:profile,error:profileError}=await admin.from("content_profiles").select("workspace_id,version").eq("is_active",true).limit(1).single();if(profileError||!profile)throw new Error(profileError?.message??"Active profile missing");
const{data:contents,error:contentError}=await admin.from("content_items").select("id,title,summary,body,author,duration_seconds,analysis_input_hash,source:sources(type,name)").eq("workspace_id",profile.workspace_id);if(contentError)throw new Error(contentError.message);
const contentHashes=new Map<string,string>();
let contentBackfilled=0;
for(const content of contents??[]){const hash=content.analysis_input_hash??sha256(JSON.stringify({title:content.title,summary:content.summary,body:content.body,author:content.author,durationSeconds:content.duration_seconds,source:content.source}));contentHashes.set(content.id,hash);if(!content.analysis_input_hash){const update=await admin.from("content_items").update({analysis_input_hash:hash}).eq("id",content.id).is("analysis_input_hash",null);if(update.error)throw new Error(update.error.message);contentBackfilled+=1;}}
const{data:transcripts,error:transcriptError}=await admin.from("transcripts").select("id,input_hash").eq("workspace_id",profile.workspace_id).eq("status","ready");if(transcriptError)throw new Error(transcriptError.message);const transcriptHashes=new Map((transcripts??[]).map(item=>[item.id,item.input_hash]));
const{data:analyses,error:analysisError}=await admin.from("creator_content_analyses").select("id,content_id,transcript_id,ai_run_id").eq("workspace_id",profile.workspace_id).eq("is_current",true);if(analysisError)throw new Error(analysisError.message);
let creatorAnalysesUpdated=0;
const contentInputHashes=new Map<string,string>();
for(const analysis of analyses??[]){const contentHash=contentHashes.get(analysis.content_id);if(!contentHash)continue;const inputHash=contentAnalysisInputHash({contentHash,transcriptHash:analysis.transcript_id?transcriptHashes.get(analysis.transcript_id):null});contentInputHashes.set(analysis.content_id,inputHash);const update=await admin.from("creator_content_analyses").update({content_hash:contentHash,input_hash:inputHash}).eq("id",analysis.id);if(update.error)throw new Error(update.error.message);if(analysis.ai_run_id){const run=await admin.from("ai_runs").update({input_hash:inputHash}).eq("id",analysis.ai_run_id);if(run.error)throw new Error(run.error.message);}creatorAnalysesUpdated+=1;}
const{data:clusters,error:clusterError}=await admin.from("event_clusters").select("id,items:event_cluster_items(content_id)").eq("workspace_id",profile.workspace_id);if(clusterError)throw new Error(clusterError.message);const eventInputHashes=new Map<string,string>();
for(const cluster of clusters??[]){const ids=(cluster.items??[]).map((item:{content_id:string})=>item.content_id).sort();const hash=sha256(ids.join(":"));eventInputHashes.set(cluster.id,hash);const update=await admin.from("event_clusters").update({analysis_input_hash:hash}).eq("id",cluster.id);if(update.error)throw new Error(update.error.message);}
const{data:eventAnalyses,error:eventAnalysisError}=await admin.from("event_analyses").select("id,cluster_id,ai_run_id").eq("workspace_id",profile.workspace_id).eq("is_current",true);if(eventAnalysisError)throw new Error(eventAnalysisError.message);let eventAnalysesUpdated=0;
for(const analysis of eventAnalyses??[]){const hash=eventInputHashes.get(analysis.cluster_id);if(!hash)continue;const update=await admin.from("event_analyses").update({input_hash:hash}).eq("id",analysis.id);if(update.error)throw new Error(update.error.message);if(analysis.ai_run_id){const run=await admin.from("ai_runs").update({input_hash:hash}).eq("id",analysis.ai_run_id);if(run.error)throw new Error(run.error.message);}eventAnalysesUpdated+=1;}
const{data:jobs,error:jobsError}=await admin.from("jobs").select("id,type,status,payload,result").eq("workspace_id",profile.workspace_id).in("type",["analyze_creator_content","analyze_competitor_content","analyze_event"]);if(jobsError)throw new Error(jobsError.message);let jobsUpdated=0;
for(const job of jobs??[]){const payload=record(job.payload);const result=record(job.result);let nextPayload=payload,nextResult=result;if(job.type==="analyze_event"){const clusterId=String(payload.clusterId??"");const inputHash=eventInputHashes.get(clusterId);if(!inputHash)continue;nextPayload={...payload,inputHash,promptVersion:EVENT_PROMPT_VERSION,profileVersion:profile.version,analysisVersion:ANALYSIS_VERSION};nextResult=Object.keys(result).length?{...result,inputHash}:result;}else{const contentId=String(payload.contentId??"");const contentHash=contentHashes.get(contentId);if(!contentHash)continue;const inputHash=contentInputHashes.get(contentId)??contentAnalysisInputHash({contentHash});nextPayload={...payload,contentHash,inputHash,promptVersion:CREATOR_PROMPT_VERSION,profileVersion:profile.version,analysisVersion:ANALYSIS_VERSION};nextResult=Object.keys(result).length?{...result,inputHash}:result;}const update=await admin.from("jobs").update({payload:nextPayload,result:Object.keys(nextResult).length?nextResult:null}).eq("id",job.id);if(update.error)throw new Error(update.error.message);jobsUpdated+=1;}
console.log(JSON.stringify({workspaceId:profile.workspace_id,contentBackfilled,creatorAnalysesUpdated,eventAnalysesUpdated,jobsUpdated}));
