"use client";
import{Save}from"lucide-react";import{useCallback,useEffect,useState}from"react";import{apiFetch}from"../../lib/client/api";
const formatOptions=["竖屏短视频","横屏教程","图文","一题多做"];const focusOptions=["AI 编程","Claude Code","Cursor","AI 工具实测","AI 工作流","AI 教程","AI 视频","AI 学习方法"];
type Profile={version:number;identityText:string;contentDirection:string;targetAudience:string;formats:string[];focusTopics:string[];excludedTopics:string[];products:string;valueCriteria:string;forbiddenContent:string[];historicalTopics:string[]};
const defaults:Profile={version:0,identityText:"AI 内容创作者、独立开发者、互联网产品经理",contentDirection:"AI 工具真实实测、AI 编程、AI 工作流、AI 教程、效果展示",targetAudience:"希望使用 AI 提升开发、工作、学习和内容创作效率的人",formats:formatOptions,focusTopics:focusOptions,excludedTopics:[],products:"",valueCriteria:"能改变具体行动；有真实证据；可以实际演示；不是重复转述；能形成教程、实测或判断；适合当前账号受众。",forbiddenContent:[],historicalTopics:[]};
function lines(value:string){return value.split("\n").map(item=>item.trim()).filter(Boolean)}
export function ContentProfileEditor(){const[profile,setProfile]=useState(defaults);const[versions,setVersions]=useState<Array<{version:number;isActive:boolean;updatedAt:string}>>([]);const[applyMode,setApplyMode]=useState("new_only");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const data=await apiFetch<{current:Profile|null;versions:Array<{version:number;isActive:boolean;updatedAt:string}>}>("/api/settings/profile");if(data.current)setProfile(data.current);setVersions(data.versions);setError(null)}catch(reason){setError(reason instanceof Error?reason.message:"读取失败")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  function toggle(field:"formats"|"focusTopics",value:string){setProfile(current=>({...current,[field]:current[field].includes(value)?current[field].filter(item=>item!==value):[...current[field],value]}))}
  async function save(){setSaving(true);setError(null);try{const data=await apiFetch<{current:Profile;requeue:{requested:number}}>("/api/settings/profile",{method:"POST",body:JSON.stringify({...profile,applyMode})});setProfile(data.current);setNotice(`画像 v${data.current.version} 已激活${data.requeue.requested?`，${data.requeue.requested} 个分析任务已重新排队`:"，只应用于新任务"}`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"保存失败")}finally{setSaving(false)}}
  return<div className="v2-page v2-profile-page"><header className="v2-page-header"><div><div className="v2-date">内容画像 · 当前 v{profile.version||"—"}</div><h1>让每次分析都围绕你的内容目标</h1><p>每次保存都会生成新版本；分析任务会记录实际使用的画像版本。</p></div></header>{error&&<div className="v2-error">{error}</div>}{notice&&<div className="v2-success">{notice}</div>}
    <section className="v2-profile-form"aria-busy={loading}><label>用户身份<textarea value={profile.identityText}onChange={e=>setProfile({...profile,identityText:e.target.value})}/></label><label>当前主要内容方向<textarea value={profile.contentDirection}onChange={e=>setProfile({...profile,contentDirection:e.target.value})}/></label><label>目标受众<textarea value={profile.targetAudience}onChange={e=>setProfile({...profile,targetAudience:e.target.value})}/></label><fieldset><legend>常做内容形式</legend>{formatOptions.map(item=><label key={item}><input type="checkbox"checked={profile.formats.includes(item)}onChange={()=>toggle("formats",item)}/>{item}</label>)}</fieldset><fieldset><legend>当前优先关注</legend>{focusOptions.map(item=><label key={item}><input type="checkbox"checked={profile.focusTopics.includes(item)}onChange={()=>toggle("focusTopics",item)}/>{item}</label>)}</fieldset><label>暂时不关注的主题<textarea value={profile.excludedTopics.join("\n")}onChange={e=>setProfile({...profile,excludedTopics:lines(e.target.value)})}placeholder="每行一个主题"/></label><label>当前业务或产品<textarea value={profile.products}onChange={e=>setProfile({...profile,products:e.target.value})}/></label><label>内容价值判断标准<textarea value={profile.valueCriteria}onChange={e=>setProfile({...profile,valueCriteria:e.target.value})}/></label><label>禁止生成的内容类型<textarea value={profile.forbiddenContent.join("\n")}onChange={e=>setProfile({...profile,forbiddenContent:lines(e.target.value)})}placeholder="每行一种"/></label><label>已经做过的历史选题<textarea value={profile.historicalTopics.join("\n")}onChange={e=>setProfile({...profile,historicalTopics:lines(e.target.value)})}placeholder="每行一个选题"/></label></section>
    <section className="v2-profile-apply"><h2>这次修改应用到哪里</h2>{[["new_only","仅应用于新内容"],["pending","重新分析所有 pending 内容"],["last_7_days","重新分析过去 7 天内容"]].map(([value,label])=><label key={value}><input type="radio"name="apply"value={value}checked={applyMode===value}onChange={()=>setApplyMode(value)}/>{label}</label>)}<button className="v2-primary"disabled={saving||loading}onClick={()=>void save()}><Save size={16}/>{saving?"正在保存":"保存为新版本并激活"}</button></section>
    <section className="v2-profile-history"><h2>版本记录</h2>{versions.map(item=><div key={item.version}><strong>v{item.version}{item.isActive?" · 当前激活":""}</strong><span>{new Date(item.updatedAt).toLocaleString("zh-CN")}</span></div>)}</section></div>}
