import { requireRequestContext } from "../../../lib/server/auth";
import { getSupabaseAdmin } from "../../../lib/server/supabase-admin";

type Direction={topic:string;type:"实测型"|"教程方法型"|"观点判断型";targetAudience?:string;painPoint?:string;triggerScene?:string;expectedResult?:string;coreViewpoint?:string;differentiatedAngle?:string;whyNow?:string;validationTask?:string;recommendedFormat?:string;risks?:string[]};
type SourceRef={type:"event"|"content"|"segment"|"note"|"knowledge_card"|"practice_task";id:string;excerpt?:string;timestampMs?:number};

export async function GET(request:Request){try{const context=await requireRequestContext(request);if(context.mode==="demo")return Response.json({mode:"demo",items:[]});const admin=getSupabaseAdmin();const{data,error}=await admin.from("topic_candidates").select("id,topic,target_audience,pain_point,trigger_scene,expected_result,core_viewpoint,differentiated_angle,why_now,validation_task,recommended_format,duplicate_score,risk,status,creation_source,created_at,sources:topic_sources(id,source_type,source_id,purpose,excerpt,timestamp_ms)").eq("workspace_id",context.workspaceId).order("created_at",{ascending:false}).limit(100);if(error)throw new Error(error.message);return Response.json({mode:"live",items:data??[]});}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"读取选题失败"},{status:500})}}

export async function POST(request:Request){try{const context=await requireRequestContext(request);if(context.mode==="demo")return Response.json({ok:true,mode:"demo",items:[]});const body=await request.json() as {directions?:Direction[];sources?:SourceRef[]};const directions=(body.directions??[]).slice(0,3);const sources=body.sources??[];if(!directions.length)return Response.json({error:"至少需要一个明确的选题方向"},{status:400});if(!sources.length)return Response.json({error:"选题必须关联至少一条真实证据"},{status:400});const admin=getSupabaseAdmin();const created=[];for(const direction of directions){if(!direction.topic.trim())continue;const{data:topic,error}=await admin.from("topic_candidates").insert({workspace_id:context.workspaceId,topic:direction.topic.trim(),target_audience:direction.targetAudience??null,pain_point:direction.painPoint??null,trigger_scene:direction.triggerScene??null,expected_result:direction.expectedResult??null,core_viewpoint:direction.coreViewpoint??null,differentiated_angle:direction.differentiatedAngle??null,why_now:direction.whyNow??null,validation_task:direction.validationTask??"补充一次真实测试并记录结果",recommended_format:direction.recommendedFormat??direction.type,risk:direction.risks??[],status:"candidate",creation_source:"manual_from_real_evidence"}).select("id,topic,status").single();if(error||!topic)throw new Error(error?.message??"创建选题失败");const relations=sources.map((source)=>({workspace_id:context.workspaceId,topic_id:topic.id,source_type:source.type,source_id:source.id,purpose:"evidence",excerpt:source.excerpt??null,timestamp_ms:source.timestampMs??null}));const stored=await admin.from("topic_sources").insert(relations);if(stored.error)throw new Error(stored.error.message);created.push({...topic,evidenceCount:relations.length,type:direction.type});}return Response.json({ok:true,mode:"live",items:created},{status:201});}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"创建选题失败"},{status:500})}}
