import assert from"node:assert/strict";import test from"node:test";import{detectMaterialChange,protectedIngestMetadata,type MaterialSnapshot}from"../../lib/services/ingest";import{clusterBaseUpdate}from"../../lib/clustering/events";import{classifyTrendWindows}from"../../lib/clustering/cross-source";import{nextWatchedMs,buildYouTubeEmbedUrl}from"../../lib/youtube/player-progress";import{sortCreatorRecommendations}from"../../lib/repositories/today";import type{CreatorItem}from"../../lib/domain/signal-desk";
const snapshot:MaterialSnapshot={title:"标题",summary:"摘要",body:"正文",contentType:"video",language:"zh-CN",chapters:[]};
test("metrics-only payload changes do not reset analysis while substantive content does",()=>{assert.equal(detectMaterialChange(snapshot,{...snapshot}),false);assert.equal(detectMaterialChange(snapshot,{...snapshot,body:"新正文"}),true);assert.equal(detectMaterialChange(snapshot,{...snapshot,chapters:[{title:"新章节"}]}),true);});
test("sync metadata cannot overwrite user state or prior analysis",()=>{assert.deepEqual(protectedIngestMetadata({userState:{isSaved:true},creatorAnalysis:{summary:"old"},transcriptStatus:"ready",untrusted:"drop"}),{userState:{isSaved:true},creatorAnalysis:{summary:"old"},transcriptStatus:"ready"});});
test("event clustering base update never owns analysis interpretations",()=>{const row=clusterBaseUpdate({workspaceId:"w",lead:{id:"1",title:"事件",summary:"原始摘要",publishedAt:null,signalScore:70,tags:["AI"]},group:[{id:"1",title:"事件",summary:"原始摘要",publishedAt:null,signalScore:70,tags:["AI"]}],published:[],inputHash:"hash"});assert.equal("interpretations"in row,false);assert.equal(row.analysis_input_hash,"hash");});
test("cross-source trend compares four time windows",()=>{assert.equal(classifyTrendWindows({last24h:2,current7d:5,previous7d:1,baseline30d:8},2),"rising");assert.equal(classifyTrendWindows({last24h:0,current7d:1,previous7d:5,baseline30d:12},2),"declining");assert.equal(classifyTrendWindows({last24h:1,current7d:1,previous7d:0,baseline30d:1},1),"isolated");});
test("watched time accumulates only while the player is actually playing",()=>{assert.equal(nextWatchedMs({watchedMs:5_000,playerState:2,lastTickAt:1_000,now:2_000}),5_000);assert.equal(nextWatchedMs({watchedMs:5_000,playerState:1,lastTickAt:1_000,now:2_000}),6_000);const src=buildYouTubeEmbedUrl("https://www.youtube.com/embed/abc",42_000,"https://desk.example");assert.match(src,/start=42/);assert.match(src,/enablejsapi=1/);});
function creator(id:string,recommendation:CreatorItem["recommendation"],learningScore:number):CreatorItem{return{id,sourceType:"youtube",platform:"YouTube",creatorName:"作者",creatorAvatarUrl:null,publishedAt:"2026-08-17T00:00:00Z",durationSeconds:600,title:id,translatedTitle:null,translatedSummary:null,translationStatus:"translating",summary:null,thumbnailUrl:null,canonicalUrl:null,contentKind:"video",hasTranscript:false,interactionAvailable:false,recommendation,metadataRecommendation:"pending",metadataBoundary:"仅依据标题与简介的初步判断",possibleValue:null,processingMode:"metadata_only",recommendationReason:null,learningTakeaways:[],topicOpportunity:null,learningScore,topicSignalScore:0,analysisMessage:null,analysisStatus:recommendation==="pending"?"pending":"ready",state:{isRead:false,isSaved:false,watchLater:false,isIgnored:false,notInterested:false,queuedLearning:false}};}
test("homepage creator recommendations prioritize value before recency",()=>{const sorted=sortCreatorRecommendations([creator("pending","pending",100),creator("topic","topic_signal",20),creator("deep","deep_learn",10),creator("scan","quick_scan",90)]);assert.deepEqual(sorted.map(item=>item.id),["deep","topic","scan","pending"]);});
