import test from "node:test";
import assert from "node:assert/strict";
import { parsePlainTranscript,parseSrt,parseVtt } from "../../lib/transcripts/manual";
import { TranscriptProviderChain } from "../../lib/transcripts/chain";
import { TranscriptUnavailableError,type TranscriptProvider } from "../../lib/transcripts/types";

test("manual transcript provider parses SRT timestamps", () => {
  const result = parseSrt("1\n00:00:01,000 --> 00:00:03,500\nHello world\n\n2\n00:00:04,000 --> 00:00:05,000\nSecond line");
  assert.equal(result.segments.length,2);
  assert.deepEqual(result.segments[0], { startMs: 1000, endMs: 3500, text: "Hello world" });
});

test("manual uploads support VTT and plain text with honest timestamp boundaries",()=>{assert.equal(parseVtt("WEBVTT\n\n00:01.000 --> 00:03.000\nHello").segments[0].startMs,1000);const plain=parsePlainTranscript("No timestamps");assert.equal(plain.hasTimestamps,false);assert.equal(plain.segments[0].endMs,0);});

test("transcript provider chain falls back after an unavailable provider",async()=>{const unavailable:TranscriptProvider={name:"first",async canHandle(){return true},async fetch(){throw new TranscriptUnavailableError("missing")}};const ready:TranscriptProvider={name:"second",async canHandle(){return true},async fetch(){return{language:"en",isAutoGenerated:false,segments:[{startMs:0,endMs:1000,text:"ok"}],provider:"second"}}};const result=await new TranscriptProviderChain([unavailable,ready]).fetch({videoId:"v",sourceUrl:"https://youtube.com/watch?v=v"});assert.equal(result.result.provider,"second");assert.equal(result.attempts[0].status,"unavailable");});
