"use client";
import{ArrowRight,Bookmark,Clock3,ExternalLink,Lightbulb,Play,RefreshCw,ThumbsDown,X}from"lucide-react";import Link from"../ui/app-link";import{useCallback,useEffect,useMemo,useState}from"react";import type{ContentAction,CreatorItem,LearningRecommendation}from"../../lib/domain/signal-desk";import{apiFetch}from"../../lib/client/api";
const recommendationLabels:Record<LearningRecommendation,string>={deep_learn:"建议深入学习",quick_scan:"建议快速浏览",topic_signal:"只作为选题信号",ignore:"可以忽略",pending:"等待分析"};const dateTime=new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"});
function duration(seconds:number|null){if(!seconds)return"时长未知";const minutes=Math.floor(seconds/60);return minutes>=60?`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,"0")}`:`${minutes} 分钟`}
export function CreatorFeed(){const[items,setItems]=useState<CreatorItem[]>([]);const[source,setSource]=useState("all");const[recommendation,setRecommendation]=useState("");const[sort,setSort]=useState<"recommended"|"published"|"creator">("recommended");const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[selected,setSelected]=useState<CreatorItem|null>(null);const[topic,setTopic]=useState("");const[angle,setAngle]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const query=new URLSearchParams({days:"7",source,sort:sort==="published"?"published":"recommended"});if(recommendation)query.set("recommendation",recommendation);const data=await apiFetch<{items:CreatorItem[]}>(`/api/creators?${query}`);setItems(data.items)}catch(reason){setError(reason instanceof Error?reason.message:"读取失败")}finally{setLoading(false)}},[source,recommendation,sort]);useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>sort==="creator"?[...items].sort((a,b)=>a.creatorName.localeCompare(b.creatorName,"zh-CN")||String(b.publishedAt).localeCompare(String(a.publishedAt))):items,[items,sort]);
  async function action(item:CreatorItem,action:ContentAction){await apiFetch(`/api/content/${item.id}/state`,{method:"POST",body:JSON.stringify({action})});setNotice(action==="queued_learning"?"已加入学习，刷新后仍会保留":action==="watch_later"?"已加入稍后看":"已记录并用于调整推荐");setItems(current=>current.map(value=>value.id===item.id?{...value,state:{...value.state,[action==="queued_learning"?"queuedLearning":action==="watch_later"?"watchLater":action==="not_interested"?"notInterested":"isSaved"]:true}}:value))}
  function openTopic(item:CreatorItem){setSelected(item);setTopic("");setAngle(item.topicOpportunity??"")}
  async function createTopic(){if(!selected||!topic.trim())return;await apiFetch("/api/topics",{method:"POST",body:JSON.stringify({directions:[{topic,type:"实测型",targetAudience:"当前账号受众",differentiatedAngle:angle,whyNow:selected.summary,validationTask:"亲自完成一次最小实测，并记录过程、失败点和结果"}],sources:[{type:"content",id:selected.id,excerpt:selected.summary}]})});setSelected(null);setNotice("选题已创建，并保留了这条博主内容作为证据")}
  return<div className="v2-page"><header className="v2-page-header"><div><div className="v2-date">过去 7 天 · YouTube 与国内竞品</div><h1>我关注的博主发了什么</h1><p>真实封面、作者、发布时间和原始链接；没有互动数据或字幕时明确标出来。</p></div><button className="v2-refresh-button"onClick={()=>void load()}><RefreshCw size={16}/>刷新内容</button></header>
    {notice&&<div className="v2-success">{notice}<button onClick={()=>setNotice(null)}><X size={14}/></button></div>}{error&&<div className="v2-error">{error}</div>}
    <div className="v2-filter-rows"><div><span>来源</span>{[["all","全部"],["youtube","YouTube"],["get_notes","抖音 / 其他"]].map(([value,label])=><button key={value}className={source===value?"active":""}onClick={()=>setSource(value)}>{label}</button>)}</div><div><span>判断</span>{[["","全部"],["deep_learn","值得优先看"],["topic_signal","可做选题"],["quick_scan","快速浏览"],["ignore","可以忽略"],["pending","等待分析"]].map(([value,label])=><button key={value}className={recommendation===value?"active":""}onClick={()=>setRecommendation(value)}>{label}</button>)}</div><div><span>排序</span><select value={sort}onChange={e=>setSort(e.target.value as typeof sort)}><option value="recommended">按推荐排序</option><option value="published">按发布时间排序</option><option value="creator">按博主分组</option></select></div></div>
    <section className="v2-creator-feed">{visible.map(item=><article key={item.id}className={item.state.notInterested||item.state.isIgnored?"muted":""}><div className="v2-feed-media">{item.thumbnailUrl?<img src={item.thumbnailUrl}alt=""/>:<div>暂无真实封面</div>}<span>{duration(item.durationSeconds)}</span></div><div className="v2-feed-copy"><header>{item.creatorAvatarUrl?<img src={item.creatorAvatarUrl}alt=""/>:<span className="creator-fallback">{item.creatorName.slice(0,1)}</span>}<div><strong>{item.creatorName}</strong><small>{item.platform} · {item.publishedAt?dateTime.format(new Date(item.publishedAt)):"发布时间不可用"}</small></div></header><h2>{item.translatedTitle??item.title}</h2>{item.translatedTitle&&<p className="original-title">原标题：{item.title}</p>}<p>{item.summary??"来源没有提供内容摘要。"}</p><div className="v2-recommendation"><strong>{recommendationLabels[item.recommendation]}</strong><span>{item.recommendationReason??(item.analysisStatus==="pending"?"尚未配置 AI Provider，当前不生成固定推荐理由。":"暂无推荐理由")}</span></div><dl><dt>值得学习</dt><dd>{item.learningTakeaways.length?item.learningTakeaways.join("；"):"等待分析"}</dd><dt>选题机会</dt><dd>{item.topicOpportunity??"等待分析"}</dd></dl><div className="v2-data-boundary"><span>{item.hasTranscript?"已有字幕":"暂无字幕"}</span><span>{item.interactionAvailable?"有互动数据":"互动数据不可用"}</span></div><footer>{item.canonicalUrl&&<a href={item.canonicalUrl}target="_blank"rel="noreferrer"><Play size={15}/>播放或查看原文<ExternalLink size={13}/></a>}<Link href={`/learning/${item.id}`}><Clock3 size={15}/>查看字幕</Link><button onClick={()=>void action(item,"queued_learning")}><Bookmark size={15}/>加入学习</button><button onClick={()=>void action(item,"watch_later")}><Clock3 size={15}/>稍后看</button><button onClick={()=>openTopic(item)}><Lightbulb size={15}/>创建选题</button><button onClick={()=>void action(item,"not_interested")}><ThumbsDown size={15}/>不感兴趣</button></footer></div></article>)}{!visible.length&&<div className="v2-inline-empty"><strong>{loading?"正在读取真实博主内容…":"当前筛选下没有内容"}</strong><p>不会用账号资料卡或固定视频补位。可调整筛选，或到来源页检查同步状态。</p></div>}</section>
    {selected&&<dialog open aria-modal="true"aria-label="创建选题"className="v2-modal-backdrop"><section className="v2-topic-modal"><button className="close"onClick={()=>setSelected(null)}><X/></button><small>证据来自 {selected.creatorName}</small><h2>创建一个明显不同的方向</h2><label>你的选题标题<input value={topic}onChange={e=>setTopic(e.target.value)}placeholder="不要只翻译或改写原标题"/></label><label>差异化角度<textarea value={angle}onChange={e=>setAngle(e.target.value)}placeholder="你会亲自测试、补充哪个场景，或提出什么判断？"/></label><p>创建后会保存真实 content ID、来源关系和时间戳。</p><button className="v2-primary"onClick={()=>void createTopic()}>创建实测型选题 <ArrowRight size={16}/></button></section></dialog>}
  </div>}
